### ISSUE TITLE
[Suggestion] Draconic Entity Type

### ISSUE THREAD

**Issue by JasdanVM** [Provismet/Extra-Damage-Enchantments#4]
It's a little difficult to group non end related Dragons with other mobs, even arcane doesn't seem to fit them, sorting them into different categories also doesn't seem like the best option, with how special the Dragon family of creatures feels, having a specialized enchantment to deal with them seems nice.

With the amount of dragons out there thanks to mods I think this enchantment and custom portrait would be more than justified.
![2024-10-28_20 55 14](https://github.com/user-attachments/assets/75f3f259-3c2b-4909-a007-ce4fb4bb5db7)

**Comment by Provismet** [comment]
Realistically speaking dragons actually fall very neatly into Beastly. Dragons are just large lizards.

Explanation:
- Fungifloral: Plant/Fungus creatures
- Outerworldly: End-related or void related. Endermen, creatures that teleport, Cthulhu, etc.
- Beastly: Animals and monsters. Anything made of meat.
- Arcane: Does not include mobs that simply *have* magic, but rather ones that are *made* from it entirely. Golems, Blazes, etc.
- Humanoid: Humans and human-like creatures.

**Comment by JasdanVM** [comment]
I'm not sure about this concept... what I mean is, Beastly encompasses a very wide arange of creatures already, and to, on top of that be useful for slaying dragons seems makes it be too good.

Also, you didn't mentioned aquatic, @Provismet 
Turtles are made out of meat, and yet you, or the game classifies them as aquatic by default, where exactly is the line drawn?
What about an aquatic Dragon? They're still fundamentally the same genome, just living on a different enviroment.

**Comment by Provismet** [comment]
1. The types are not mutually exclusive, each one is just a datapack tag. This is true for mods and vanilla. So a mob can be both Beastly and Aquatic (I have intentionally avoided this, but it can happen.)
2. Aquatic is a vanilla group, so I draw the line at whether Mojang themselves added it to Aquatic or not. In general anything that lives in water is Aquatic.
3. Beastly is wide in principle but not in use-case. Gameplay is the most important factor; vanilla has very few Beastly mobs that actually matter, in modded contexts there are typically only a few animalistic hostiles too. Dragons help to pad the numbers. I'm not adding Draconic.
